steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/mugen-backend', './backend']
    
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mugen-backend']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'mugen-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/mugen-backend'
      - '--region'
      - 'europe-west1'
      - '--allow-unauthenticated'
      - '--max-instances'
      - '1'
      - '--session-affinity'

images:
  - 'gcr.io/$PROJECT_ID/mugen-backend'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
